//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebAPIPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISROT_LEMORIM
    {
        public long SEQ_NUM { get; set; }
        public int ZEHUT { get; set; }
        public int KOD_MISRA { get; set; }
    }
}
