//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebAPIPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORIM
    {
        public int ZEHUT { get; set; }
        public string SHEM { get; set; }
        public string CTOVET { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONE { get; set; }
    }
}
